
name: build-and-test

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2   
      
      - name: Setting up Python Env
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies    
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.0
          
      - name: Execute Tests
        run: |
          cd user_crud
          pytest

