on: pull-request

jobs:
   example_comment_pr:
      runs-on: ubuntu-latest

      name: Commenting on PR
         steps:
         
          - name: Checkout
            uses: actions/checkout@v2
 
          - name: Comment PR
            uses: thollander/actions-comment-pull-request@master
            with:
             message: 'Example of message !'
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
